name: food-project
type: php
docroot: public
php_version: '8.0'
webserver_type: nginx-fpm
router_http_port: '8080'
use_dns_when_possible: true
xdebug_enabled: false
db: mysql
db_version: '8.0'

hooks:
	post-start:
		- exec: "bash -lc 'if [ -f package.json ]; then npm ci --no-audit --no-fund; fi'"
